stages:
  - build
  - push

build:
  stage: build
  script:
    - docker build --rm -t gpii/version-updater .

push:
  stage: push
  script:
    - docker push gpii/version-updater
  only:
    - master@gpii-ops/gpii-version-updater
